# -*- coding: utf-8 -*-
"""
Created on Mon Feb 20 09:24:39 2023

@author: Angela
"""
from block import DEFAULT_KWARGS_BLOCK
from ischemia import DEFAULT_OPTIONS_ISC
import plotblock 
from sliders import add_sliders
import getischemia

def plot_ischemia(opt, pl, sliders):
    """
    Plots an ischemia simulation based on the data obtained by the get_scalars() function 
    on a grid mesh generated by the plot_block() function.

    Args:
    ----
        opt : str
            Type of geometry to use for the simulation.
        pl : bool
            If True, displays the plot.
        sliders : bool
            If True, add sliders to control the simulation parameters interactively.

    Returns:
    -------
        pyvista.StructuredGrid : 
            The grid mesh used to plot the ischemia simulation.
    """

    KWARGS_ISC = {
    name: DEFAULT_OPTIONS_ISC[opt][name]['value'] for name in DEFAULT_OPTIONS_ISC[opt].keys()}

    grid_mesh, plotter = plotblock.plot_block()
    grid_mesh['scalars'] = getischemia.get_scalars(opt, grid_mesh.points, KWARGS_ISC)
    plotter.add_mesh(grid_mesh, show_scalar_bar=False if sliders else True)
    
    if sliders:
        add_sliders(opt, plotter, grid_mesh)
    if pl:
        plotter.show()
    return grid_mesh
    

def grid_updatter(opt, d, sx=DEFAULT_KWARGS_BLOCK['sx'], sy=DEFAULT_KWARGS_BLOCK['sy'], sz=DEFAULT_KWARGS_BLOCK['sz'],
                  dx=DEFAULT_KWARGS_BLOCK['dx'], dy=DEFAULT_KWARGS_BLOCK['dy'], dz=DEFAULT_KWARGS_BLOCK['dz']):
    """
    Generates a new 'pyvista.StructuredGrid' object based on 
    the input parameters and the updated ischemia data. 

    Args:
    ----
        opt : str
            Type of geometry to use for the simulation.
        d : dict
            Dictionary with the updated data of the mesh.
        sx : float, optional
            Size of the mesh in the x direction. Default is set to 'DEFAULT_KWARGS_BLOCK['sx']'.
        sy : float, optional
            Size of the mesh in the y direction. Default is set to 'DEFAULT_KWARGS_BLOCK['sy']'.
        sz : float, optional
            Size of the mesh in the z direction. Default is set to 'DEFAULT_KWARGS_BLOCK['sz']'.
        dx : float, optional
            Spacing between points in the x direction. Default is set to 'DEFAULT_KWARGS_BLOCK['dx']'.
        dy : float, optional
            Spacing between points in the y direction. Default is set to 'DEFAULT_KWARGS_BLOCK['dy']'.
        dz : float, optional
            Spacing between points in the z direction. Default is set to 'DEFAULT_KWARGS_BLOCK['dz']'.

    Returns:
    -------
        pv.StructuredGrid : 
            A 'pyvista.StructuredGrid' object representing the updated mesh.
    """
    grid = plotblock.create_grid_mesh(sx, sy, sz, dx, dy, dz)
    grid['scalars'] = getischemia.get_scalars(opt, grid.points, d)
    return grid
